// command_ask.js

module.exports = {
  thinking: [
    "hmm...",
    "uhhhhh...",
    "one sec...",
    "ehhhh...",
    "let me think about it...",
    "shh let me think!!",
    "umm...",
    "lemme see...",
    "first add the 7, carry the 1, add that, mhmm...",
    "processing...",
    "give me a sec to think about it...",
    "good question! uhh...",
    "let me check real quick...",
    "are you sure you want an answer to that? okay...",
    "hold still...",
    "i mean... since you asked so nicely..."
  ],
  answer: [
    "sure!",
    "ya right",
    "i refuse to answer >:(",
    "yes!!",
    "i think so yea",
    "perhaps maybe quite possibly",
    "ask me later, i'm eating tacos rn",
    "pfffftftpfhpfhfttfhthhthffpfffth",
    "honestly idk lol sry xd",
    "NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO",
    "ok ya definitely not lol",
    "ok",
    "no",
    "on second thought i gtg bye",
    "420",
    "69",
    "over 9000",
    "don't ask me, i'm just a bot... or am i O_O",
    "no u",
    "42",
    "google is your friend :)",
    "duh",
    "ask me again pls i wasn't paying attention",
    "can't answer, cranking 90s rn",
    "that sounds like a you problem",
    "i don't feel like answering that... sorry not sorry xd",
    "i'm busy right now, can i ignore you another time?",
    "i'd agree with you but then we'd both be wrong",
    "idk but what i do know is that supsup is the best :)"
  ]
};